/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "faydzugbcupyitkaptyl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZheWR6dWdiY3VweWl0a2FwdHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMzQ0MjgsImV4cCI6MjA3NTcxMDQyOH0.J-lFP0MmveL16ByLXkMAJAnv7c-nIji8DxNVx_ma4EE"